### ISSUE TITLE
Suggesting another way to enable survival mod

### ISSUE THREAD

**Issue by bisqunours** [BadlionClient/BadlionClientModAPI#30]
Hello, 
To enable the survival mod, you have to install the badlion API on your server which can sometimes be long and pain for players (as it require spigot or smth like that tho). 

I suggest a thing that would enable the survival mod on a server if an OP player of the server does a command such as /blc survivalmod on/off to activate the survival mod for everybody. 

As the survival mod is a thing that is used by a lot of players who sometimes just have a basic server and who don't want to spend time on installing an API I think that it could be a cool addition to the client.

**Comment by PSNRigner** [comment]
Hey,

The only requirement for our plugin is Craftbukkit, which is required for any kind of plugin, there's no other way since Vanilla minecraft doesn't support plugins.

We already have a easy command to toggle the Survival mod through a menu, and it's as easy as installing any other plugin: `/survivalapi`
